### ISSUE TITLE
Feature Request: Retrieve Questionnaires, Messages, and Total Activity per Experiment

### ISSUE THREAD

**Issue by Meefish** [UtrechtUniversity/wildlifenl#25]
We need to extend the functionality of fetching experiments to include additional data for each experiment:

- The number of associated **Questionnaires**.
- The number of associated **Messages**.
- The **Total number of Activity**, needs to be calculated as the sum of (make the API able to fetch both of the values underneath since calculations can be done with logic):
  - Submitted Questionnaires (with a minimum of 1 answer).
  - Messages sent.

**Comment by BasMichielsen** [comment]
I will make two separate fields for activity, you can sum them together if you want.
