### ISSUE TITLE
Remove "displayNameUser" requirement from POST /auth request

### ISSUE THREAD

**Issue by Meefish** [UtrechtUniversity/wildlifenl#26]
Currently, the `POST /auth` endpoint requires the `displayNameUser` field, which is unnecessary for users logging in with an OTP. It becomes repetitive for users to provide their display name every time they log in with an OTP. To simplify the login process, the `displayNameUser` field should be removed as a requirement for authentication.

**Comment by BasMichielsen** [comment]
Agree, for the first login that automatically creates and account, the user name can be inferred from email address just grabbing everything before the @ symbol. This is a little less elegant in the email message, currently it says something like "Hi Bas", and then it would be "Hi b.michielsen" or something like that. But it simplifies the login procedure.
