### ISSUE TITLE
Issue: Configure CORS Policy to Allow Specific Application Domains

### ISSUE THREAD

**Issue by Meefish** [UtrechtUniversity/wildlifenl#27]
The *CORS (Cross-Origin Resource Sharing) policy* on the server currently does not allow specific domains to access the API. This results in CORS errors when the front-end applications attempt to make API requests. To resolve this, we need to configure the server to include the necessary domains in the `Access-Control-Allow-Origin` header.

**Comment by bshtmichielsen** [comment]
A possible solution is to add a middleware for CORS related calls. Here is a snippet:

```Go
func corsMiddleware(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        // Set CORS headers
        w.Header().Set("Access-Control-Allow-Origin", "*")
        w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        w.Header().Set("Access-Control-Allow-Headers", "Content-Type")

        // Handle preflight requests
        if r.Method == http.MethodOptions {
            w.WriteHeader(http.StatusNoContent)
            return
        }
        next.ServeHTTP(w, r)
    })
}
```

**Comment by BasMichielsen** [comment]
I made a first attempt to fix this but I cannot test it easily. Can you test it against API v20241013? 
Reopen this issue if it does not work yet.

**Comment by BasMichielsen** [comment]
Did not work yet, because the huma middleware gets called AFTER it has decided that the method is not valid.

**Comment by Meefish** [comment]
The Options Preflight Request gives a 200 OK Response. But after that this issue arises:

*Access to fetch at 'https://wildlifenl-uu-michi011.apps.cl01.cp.its.uu.nl/auth/' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.*

I recommend adding this code to solve this problem: 
`w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")`

**Comment by Meefish** [comment]
The request for the OTP Password went through, but authenticating with the code contains the following issue:

*Access to fetch at 'https://wildlifenl-uu-michi011.apps.cl01.cp.its.uu.nl/auth/' from origin 'http://localhost:3000' has been blocked by CORS policy: Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.*

Please try adding this code to solve this problem:
`w.Header().Set("Access-Control-Allow-Methods", "POST, GET, PUT")`

**Comment by BasMichielsen** [comment]
I will add "GET", "POST", "GET" and "DELETE" but they do not always match the end-point that the preflight is made against.
