### ISSUE TITLE
Feature Request: Ability to Delete or Toggle Questionnaire State (Live/Offline)

### ISSUE THREAD

**Issue by Meefish** [UtrechtUniversity/wildlifenl#29]
The platform should support more management for questionnaires by providing the ability to:

- Delete a questionnaire
- Toggle the state of a questionnaire between `Live` and `Offline`

**Comment by BasMichielsen** [comment]
This is inherit by the Experiment they belong to. An experiment has a start and end date and thus decides for all Questionnaires and Messages whether they are active or not. Toggling within those dates makes for dodgy research results.

**Comment by BasMichielsen** [comment]
Conceptual mismatch with design.

**Comment by BasMichielsen** [comment]
Conceptual mismatch with design.
