### ISSUE TITLE
Feature Request: Slider Option for Questionnaire 

### ISSUE THREAD

**Issue by Meefish** [UtrechtUniversity/wildlifenl#41]
Implement a slider option for the questionnaire, allowing researchers to select a value within a specified range. The slider should have a defined minimum (`x1`) and maximum (`x2`) value. Additionally, implement logic to ensure that `x1` (minimum) cannot be greater than `x2` (maximum) + No `negative values`

**Comment by BasMichielsen** [comment]
The API does not dictate how the client application should represent things, only the required format of the input data. 

Let's add a field `format` to a Question against which the free format text of a Response must be validated.

**Comment by BasMichielsen** [comment]
In your UI you could provide a selection of possible formats:

integer 1 - 100:
^[1-9]$|^[1-9][0-9]$|^(100)$
