### ISSUE TITLE
Issue: Fetching "My Experiments" Fails (500 Internal Server Error)

### ISSUE THREAD

**Issue by Meefish** [UtrechtUniversity/wildlifenl#44]
The OTP process is working as expected, but fetching the "My Experiments" endpoint results in a 500 Internal Server Error.

**Error Details:**  
**Request URL:** https://wildlifenl-uu-michi011.apps.cl01.cp.its.uu.nl/experiments/me/  
**Request Method:** GET  
**Status Code:** 500 Internal Server Error  
**Remote Address:** 131.211.51.3:443  
**Referrer Policy:** strict-origin-when-cross-origin

**Comment by BasMichielsen** [comment]
Hotfixed in version 20241017
