### ISSUE TITLE
Add: endpoint Stop Experiment 

### ISSUE THREAD

**Issue by Meefish** [UtrechtUniversity/wildlifenl#49]
A way to set the End timestamp of an experiment to NOW().

**Comment by BasMichielsen** [comment]
This can be done using `Update Experiment` by providing all fields the same as the current value, and adding the optional field `end`. You can call the `time.now()` equivalent in your client and provide that as the value for `end`.

**Comment by Meefish** [comment]
The API Documentation States: `Update an existing experiment that has not started yet.` 

This doesn't add up to the use case to stop an experiment earlier.

**Comment by BasMichielsen** [comment]
You are right, if the Experiment has started, the endpoint Update Experiment should reject your requests, yet, you cannot stop an experiment early when it did not start yet. I will reopen this issue.
