### ISSUE TITLE
Add extra fields to `Profile`

### ISSUE THREAD

**Issue by MarkvdKort** [UtrechtUniversity/wildlifenl#59]
- Leeftijd
- Geslacht
- Postcode
- Rol

**Comment by BasMichielsen** [comment]
Hi Mark, I reckon this is on the `profile` endpoints, not on `user`. Also your fields are ambiguous:
`Leeftijd` should probably be `DateOfBirth`, as `Age` changes every year, but `DateOfBirth` does not.
`Geslacht` is a difficult field, do you mean `Gender` or `Sex`? What does the product owner expect here as possible inputs?
`Postcode` is fine
`Rol` What does this mean, should it be a free format text field?

**Comment by MarkvdKort** [comment]
Hi Bas, the list I named here is simply the list I received from the product owners. I did not think this out into detail since I am not responsible for building the backend. But like you said yes using date of birth would be better than just using age. 

Role should probably become a free format text field since this will mostly be about the job of the user which can not be chosen easily from a preset list of values. 

For Gender I would assume that Man, Women, Other or "I prefer not to say" should be sufficient but we will check that with the product owners. For now it would be nice if you could create an endpoint in which we can retrieve the different available genders so that this can always be easily modified.

**Comment by BasMichielsen** [comment]
Let's just ask the product owner for a list. It makes little sense that you and I devise something.
