### ISSUE TITLE
Internal Server Error Status 500: When trying to stop a `Live Experiment`

### ISSUE THREAD

**Issue by Meefish** [UtrechtUniversity/wildlifenl#72]
Error Message:

Error stopping experiment: Error: Failed to end experiment: {"$schema":"https://wildlifenl-uu-michi011.apps.cl01.cp.its.uu.nl/schemas/ErrorModel.json","title":"Internal Server Error","status":500}

**Comment by Meefish** [comment]
It happens when the ID is not correctly passed. The error message is wrong, but it's mostly a client side issue.

**Comment by BasMichielsen** [comment]
There was a typo on the back-end, the parameter name should be `id` but it was `ID`. This is now fixed. 
Please do check your call, perhaps yours was sending `id` fine, and the issue was only on my end.
